title: gu1233 Portfolio
name: 구다은
email: gde102@naver.com
description: 신입 개발자 구다은 포트폴리오입니다.

baseurl: ""
url: "https://gu1233.github.io"

display_footer: none  #change this to 'none' if you want to hide the footer copyright text

parallax_image_one: assets/images/startup3.jpg # These are the images used for the parallax background
parallax_image_two: assets/images/startup3.jpg

project_one: Online Bookstore
project_one_description: 개발기간 - 2020.01.16 ~ 2020.01.30<br>개발인원 - 5명<br>로그인, 회원가입, 판매관리, 게시판, 리뷰 등의 기능이 구현된 간단한 온라인 서점입니다.<br>이 중 공지사항 게시판 crud 기능을 맡아 구현하였습니다.
project_one_url: https://github.com/sungyoonkim930316/TeamBook4.git
project_one_icon: location_on

project_two: TEAMPLAN
project_two_description: 개발기간 - 2020.04.20 ~ 2020.05.11<br>개발인원 - 5명<br>워크스페이스 생성, 프로젝트 및 업무관리, 피드백 등의 기능이 구현된 협업툴입니다.<br>이 중 로그인, 회원가입 기능을 맡아 구현하였습니다.
project_two_url: https://github.com/team200330/team.git
project_two_icon: book

portfolio_heading: Portfolio
portfolio_type: cards

project_button: Github

AboutMe_title: 잘하는 개발자
AboutMe_description1: 어렸을 때부터 결과물을 도출해내는 일에 흥미가 많았습니다.<br>우연치않게 주변 IT관련된 지인들로부터 이 분야를 접하게 되어 시작하게 되었습니다.<br>제가 만들어낸 결과물을 볼수록 흥미가 생기고 더 잘하고 싶다는 생각이 들었습니다. 
AboutMe_description2: 저는 경력만 쌓는 개발자가 아닌 항상 노력하고 성장하여 잘하는 개발자가 되는 것이 목표입니다.<br>현재는 막 걸음마를 뗸 초보자이지만 그만큼 성장의 여지가 크다고 생각하고<br>꾸준히 공부하여 잘하는 개발자로 남고싶습니다.

syntax_highlighting: true # include the css for syntax highlighting

# Build settings
markdown: kramdown
# theme: minima
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier
