title: Developer
name: 구다은
email: gde102@naver.com
description: 신입 개발자 구다은 포트폴리오입니다.

baseurl: ""
url: "https://gu1233.github.io"

display_footer: none  #change this to 'none' if you want to hide the footer copyright text

parallax_image_one: assets/images/startup3.jpg # These are the images used for the parallax background
parallax_image_two: assets/images/startup3.jpg

project_one: Online Bookstore
project_one_description: 개발기간 - 2020.01.16 ~ 2020.01.30|개발인원 - 5명|로그인, 회원가입, 판매관리, 게시판, 리뷰 등의 기능이 구현된 간단한 온라인 서점입니다.|이 중 공지사항 게시판 crud 기능을 맡아 구현하였습니다.
project_one_url: https://github.com/sungyoonkim930316/TeamBook4.git
project_one_icon: location_on

project_two: TEAMPLAN
project_two_description: 개발기간 - 2020.04.20 ~ 2020.05.11|개발인원 - 5명|워크스페이스 생성, 프로젝트 및 업무관리, 피드백 등의 기능이 구현된 협업툴입니다.|이 중 로그인, 회원가입 기능을 맡아 구현하였습니다.
project_two_url: https://github.com/team200330/team.git
project_two_icon: book

portfolio_heading: Portfolio
portfolio_type: cards

syntax_highlighting: true
# Skill icons from https://konpa.github.io/devicon/

skills:
   - name: amazonwebservices
  - name: android
  - name: angularjs
  - name: apache
  - name: appcelerator
  - name: apple
  - name: atom
  - name: babel
  - name: backbonejs
  - name: bitbucket
  - name: bootstrap
  - name: bower
  - name: c
  - name: chrome
  - name: codeigniter
  - name: coffescript
  - name: confluence
  - name: cplusplus
  - name: csharp
  - name: css3
  - name: cucumber
  - name: d3js
  - name: debian
  - name: devicon
  - name: django
  - name: docker
  - name: doctrine
  - name: dot-net
  - name: drupal
  - name: erlang
  - name: facebook
  - name: firefox
  - name: foundation
  - name: gatling
  - name: gimp
  - name: git
  - name: github
  - name: gitlab
  - name: go
  - name: google
  - name: gradle
  - name: grunt
  - name: gulp
  - name: heroku
  - name: html5
  - name: ie10
  - name: illustrator
  - name: inkscape
  - name: itellij
  - name: java
  - name: jasmine
  - name: javascript
  - name: laravel
  - name: less
  - name: linux
  - name: meteor
  - name: mocha
  - name: mongodb
  - name: moodle
  - name: mysql
  - name: nginx
  - name: nodejs
  - name: nodewebkit
  - name: oracle
  - name: photoshop
  - name: php
  - name: phpstorm
  - name: protractor
  - name: postgresql
  - name: python
  - name: pycharm
  - name: rails
  - name: react
  - name: redhat
  - name: redis
  - name: ruby
  - name: rubymine
  - name: safari
  - name: sass
  - name: sequelize
  - name: slack
  - name: sourcetree
  - name: ssh
  - name: swift
  - name: symfony
  - name: tomcat
  - name: travis
  - name: trello
  - name: twitter
  - name: typescript
  - name: ubuntu
  - name: vim
  - name: visualstudio
  - name: vuejs
  - name: webpack
  - name: webstorm
  - name: windows8
  - name: wordpress
  - name: yii
  - name: zend

icon_size: 100 # font-size of icons in px
colored: colored # Leave blank for black and white icons

project_button: Github


baseurl: "" # if your site is located at /blog or /home, enter it here, otherwise leave it empty
url: "https://gu1233.github.io" #the url of your site



syntax_highlighting: true # include the css for syntax highlighting

# Build settings
markdown: kramdown
# theme: minima
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier
